### PR TITLE
add assembling and archiving to gensolve

### PR DESCRIPTION
**Pull request by scopatz**
Some improvements that may help compile times by offloading them to the generating machine.

### CODE REVIEW

**Comment by asmeurer** [comment]
Interesting

**Comment by scopatz** [comment]
It'd be nice to add clang hooks too, but I didn't have time on my flight and that can be a separate PR.

**Comment by scopatz** [comment]
Also, I should note that in rough timings on my laptop it seems to take 120 sec to compile the latest version to assembly, while it only takes 3 sec to go from assembly to object code. I think this will be a real win for the pyne folks who are complaining about long compile times.

**Comment by asmeurer** [comment]
Does this require cross compilation?

**Comment by scopatz** [comment]
I don't think so. Doesn't Cross compiling affect machine code, not assembly.

**Comment by scopatz** [comment]
Any other thoughts @asmeurer? This is blocking some PyNE improvements...

**Comment by asmeurer** [comment]
If it works for PyNE let's merge it.

**Pull request merged**
